name: LuoChuanRedPacket
main: com.xbaimiao.luochuan.redpacket.LuoChuanRedPacket
version: '1.1.8'
author: xbaimiao
api-version: 1.13
update-info: '修复运气王消息'
depend:
  - Vault
  - PlayerPoints
commands:
  luochuanredpacket:
    aliases:
      - lcrp
      - hb
      - hongbao
    permission: luochuanredpacket.command
