name: LuoChuanRedPacket
main: com.xbaimiao.luochuan.redpacket.LuoChuanRedPacket
version: '1.2.1'
author: xbaimiao
api-version: 1.13
update-info: '修复报错'
depend:
  - Vault
  - PlayerPoints
commands:
  luochuanredpacket:
    aliases:
      - lcrp
      - hb
      - hongbao
      - redpacket
    permission: luochuanredpacket.command
