name: LuoChuanRedPacket
main: com.xbaimiao.luochuan.redpacket.LuoChuanRedPacket
version: '1.1.1-SNAPSHOT'
author: xbaimiao
api-version: 1.13
update-info: '修复口令红包提示 [你的手速太快了,请稍后再试] 的问题'
depend:
  - Vault
  - PlayerPoints
commands:
  luochuanredpacket:
    aliases:
      - lcrp
      - hb
      - hongbao
    permission: luochuanredpacket.command
