name: LuoChuanRedPacket
main: com.xbaimiao.luochuan.redpacket.LuoChuanRedPacket
version: '1.1.2-SNAPSHOT'
author: xbaimiao
api-version: 1.13
update-info: '新增不配置不死图腾动画不调用IA'
depend:
  - Vault
  - PlayerPoints
commands:
  luochuanredpacket:
    aliases:
      - lcrp
      - hb
      - hongbao
    permission: luochuanredpacket.command
