name: EmoGuRedPacket
main: com.xbaimiao.luochuan.redpacket.LuoChuanRedPacket
version: '${version}'
author: xbaimiao
api-version: 1.13
depend:
  - Vault
  - PlayerPoints
commands:
  luochuanredpacket:
    aliases:
      - emhb
    permission: luochuanredpacket.command