name: LuoChuanRedPacket
main: com.xbaimiao.luochuan.redpacket.LuoChuanRedPacket
version: '1.1.6-SNAPSHOT'
author: xbaimiao
api-version: 1.13
update-info: '运气王消息延迟发送'
depend:
  - Vault
  - PlayerPoints
commands:
  luochuanredpacket:
    aliases:
      - lcrp
      - hb
      - hongbao
    permission: luochuanredpacket.command
