name: LuoChuanRedPacket
main: com.xbaimiao.luochuan.redpacket.LuoChuanRedPacket
version: '1.0.5'
author: xbaimiao
api-version: 1.13
depend:
  - Vault
  - PlayerPoints
commands:
  luochuanredpacket:
    aliases:
      - lcrp
      - hb
      - hongbao
    permission: luochuanredpacket.command
